var app = new Vue(
   {
      el: "#app",
      data:{
         testimonials:[
            {  avatar: "02",
               name: "Florence Themes",
               feedTitle: "It's a choice of quality for people with special needs",
               feed:	"I'm a very strict person so I require everything to be organized and neat. Then, I'll be able to make things right and shine. MaxCoach guys just got me.",
               job: "Multimedia Admin",
            },
            {  avatar: "04",
               name: "Mina Hollace",
               feedTitle: "High level of efficiency and scientific teaching methods",
               feed:	"I am free to learn at my own pace, follow my own schedule and choose the subject I want to learn from the syllabus. Great study portal for people like me.",
               job: "Freelancer",
            },
            {  avatar: "03",
               name: "Luvic Dubble",
               feedTitle: "The MaxCoach team works really hard to ensure high quality",
               feed:	"I am happy with their arrangement of lessons and subjects. They reflect a scientific  investigation into effective methods to be adopted for learners of all levels.",
               job: "Private Tutor",
            },
            {  avatar: "01",
               name: "Madley Pondor",
               feedTitle: "The MaxCoach team works really hard to ensure high quality",
               feed:	"I need to get a certification for English proficiency and MaxCoach is my best choice. Their tutors are smart and professional when dealing with students.",
               job: "IT Specialist",
            },
         ],
         testimonialsIndex: 0,
      },
   },
);